[package]
name = "code-judge"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = {version ="2.9", features= ["json"]}
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
anyhow = "1.0"
